[Feature] Localization API
Kasuromi/GTFO-API pull request #50
Opened 2023-08-02 05:39 UTC by Panthr75

Localization in GTFO on the plugin side has been a big pain. As a result, an API that plugin developers can use has been added to handle localization in a similar format to how Minecraft handles languages via separate lang files.

## Examples
Using the following `lang.en.resx` file:
![image](https://github.com/Kasuromi/GTFO-API/assets/29237603/3ce8d82e-7f76-4dc2-888d-b5953ad3fa81)
and class
```cs
internal class EntryPoint : BasePlugin
{
    public override void Load()
    {
        LocalizationAPI.LoadFromResources("MyCoolPlugin.Resources.lang");
        EventAPI.OnAssetsLoaded += OnAssetsLoaded;
    }
    private void OnAssetsLoaded()
    {
        Log.LogInfo(LogLocalizationAPI.GetString("mycoolplugin.startup_message"));
    }
}
````
Outputs:
```
[MyCoolPlugin:Info] Hello, world!
```

2023-08-02 08:01 UTC, Flowaria requested changes
Mostly looks fine for me, But have some questionable parts

2023-08-02 21:14 UTC, Panthr75 commented on GTFO-API/API/LocalizationAPI.cs
> +                Chinese_Simplified = GetStringOrDefault(Language.Chinese_Simplified, key),
How would you recommend going about that, as for loading via ResourceManager, you can't neccessarily specify a fallback

2023-08-03 14:25 UTC, Flowaria requested changes
`GetString` API returning key value bit feels awkward, but rest of change looks great except some nitpicks

2023-08-03 14:25 UTC, Flowaria commented on GTFO-API/API/LocalizationAPI.cs
> +            return key;
I think it's better throw exception here instead of just returning key value

2023-08-03 14:25 UTC, Flowaria commented on GTFO-API/API/LocalizationAPI.cs
> +                value = null;
I think it's better return fallback value instead of null here.

2023-08-03 14:25 UTC, Flowaria commented on GTFO-API/API/LocalizationAPI.cs
> +            return key;
I think it's better throw exception here instead of just returning key value

2023-08-03 14:25 UTC, Flowaria commented on GTFO-API/API/LocalizationAPI.cs
> +        if (language < Language.English || language > Language.Chinese_Simplified)
`Enum.IsDefined<Language>(language)`

2023-08-03 14:25 UTC, Flowaria commented on GTFO-API/API/LocalizationAPI.cs
> +                if (language < Language.English || language > Language.Chinese_Simplified)
`Enum.IsDefined<Language>(language)`

2023-08-04 00:57 UTC, Flowaria approved these changes
Looks good for me

2023-08-04 01:01 UTC, merged